### ISSUE TITLE
Cdir type should be named Cidr instead

### ISSUE THREAD

**Issue by Kars-de-Jong** [ebean-orm/ebean-types#2]
The class name for the `Cdir` type is wrong. Since it is to be used for storing values of `cidr` type columns, it should be name `Cidr` instead.
(FYI: CIDR means [Classless Inter-Domain Routing](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)).

**Comment by Kars-de-Jong** [comment]
This also applies to some of the other Ebean repositories by the way.
Do you want me to create separate issues for those?

**Comment by rbygrave** [comment]
`Cidr` Oh darn, yes !!

> other Ebean repositories

I don't understand this part. Repositories such as ?

**Comment by rbygrave** [comment]
Ok, the Cidr was also stored as `INET` rather than `CIDR` so also fixing that with #1880

I'll close this.  Update with what "other Ebean repositories" means - thanks.

**Comment by Kars-de-Jong** [comment]
> `Cidr` Oh darn, yes !!
> 
> > other Ebean repositories
> 
> I don't understand this part. Repositories such as ?

https://github.com/ebean-orm/ebean, but I see you already fixed it :-)

Oh, the README.md still contains the typo. Sorry...

**Comment by rbygrave** [comment]
Cool - fixed readme and summary.  Should be all good now.  Thanks!!

**Comment by Kars-de-Jong** [comment]
A colleague of mine found out that the src/main/java/io/ebeaninternal/server/type/ScalarTypeCdir.java (and its javadoc) still has the wrong name... Sorry...

**Comment by rbygrave** [comment]
> ScalarTypeCdir.java (and its javadoc) still has the wrong name... Sorry...

Thanks and great work spotting that.  It's good to get it right right !!  Sorted now.

Cheers, Rob.

**Comment by rbygrave** [comment]
Adding reference to: https://github.com/ebean-orm/ebean/issues/1880
